config/routes.rb
Rails.application.routes.draw do
  resources :locations

end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :full_street_address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates

def full_street_address
	"#{street_address}, #{city}, GA"
end

end

# from locations/_form
#    <%= f.input :lattitude %>
#    <%= f.input :longitude %>

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  include LocationsHelper
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    #marta's api url
    source_url = "http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus"
    #use helper method to parse data nto an array for all buses
    @buses = fetch_buses_from_api(source_url)
    #only get nearby buses
    @buses.select! do |bus|
      is_nearby?(@location.latitude, @location.longitude, bus["LATITUDE"], bus["LONGITUDE"])
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:street_address, :city, :lattitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
	# parse api data to store in a ruby array of hashes - with each bus as a hash
	def fetch_buses_from_api(source_url)
		http = Net::HTTP.get_response(URI.parse(source_url))
		data = http.body
		JSON.parse(data)
	end

	def is_nearby?(user_lat, user_long, bus_lat, bus_long)
		max_distance = 0.01
		difference_of_latitudes = user_lat - bus_lat.to_f

		difference_of_longitudes = user_long - bus_long.to_f

		distance = Math.sqrt(difference_of_latitudes ** 2 + difference_of_longitudes ** 2)
		
		distance <= max_distance

	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :street_address, label: 'Address or Approximate Location' %>
    <%= f.input :city %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , class: "btn btn-info btn-lg" %>

  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Street address</th>
      <th>City</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.street_address %></td>
        <td><%= location.city %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>
<p>Give us your address so we can find the nearest bus to you!</p>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Choose your bus!</h1>

<h3 class="text-muted">Your current location</h3>
<p class="text-muted">
	<%= @location.full_street_address %> <%= link_to fa_icon('pencil', text: 'Edit'), edit_location_path(@location) %>
</p>

<div id="map" style="height:500px;width:500px;margin:0;padding:0;"></div>
<script>
var map, mapOptions;
     function initMap() {
       var userLatLng = {
         lat: <%= @location.latitude %>,
         lng: <%= @location.longitude %>
       };

       var nearbyBuses = <%= raw @buses.to_json %>;
      // var busIcon <%= image_path 'bus.png' %>;
     //  var guyIcon <% image_path 'guy.png' %>;
       mapOptions = {
         center: userLatLng,
         zoom: 14
       };

       map = new google.maps.Map(document.getElementById('map'), mapOptions);

       var userMarker = new google.maps.Marker({
         position: userLatLng,
         map: map,
         animation: google.maps.Animation.DROP,
         title: "You are here."
       });

       var userInfo = '<div id="content">' + '<h3>' + '<%= @location.full_street_address %>' + '</h3>' + '</div>';
       var userWindow = new google.maps.InfoWindow({
        content: userInfo
       });

       nearbyBuses.forEach(function (element){
        var busLatLng = new google.maps.LatLng(element['LATITUDE'], element['LONGITUDE']);

        var busMarker = new google.maps.Marker({
          position: busLatLng,
          map: map,
         // icon: busIcon,
          animation: google.maps.Animation.DROP,
          title: element['ROUTE']
        });

 var busInfo =
  '<div id=content>' + '<h3>Bus ' + element['ROUTE'] + ' ' + element['DIRECTION'] + '</h3>' + '<div id="bodyContent">' + '<p>Next Stop:' + element['TIMEPOINT'] + '</p>' + '</div>' + '</div>' ;

  var busWindow = new google.maps.InfoWindow({
    content: busInfo
  });

  google.maps.event.addListener(busMarker, 'mouseover', function(){
    busWindow.open(map, busMarker);
  });
  google.maps.event.addListener(userMarker, 'mouseover', function(){
    userWindow.open(map, userMarker);
  });

       });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_maps_api_key'] %>&callback=initMap"
   async defer></script>


<h3>The closest buses to you</h3>

<% @buses.each do |bus| %>
  <p>
    <strong>Route: </strong> <%= bus["ROUTE"] %> <%= bus["DIRECTION"] %><br>
    <strong>Bus Number: </strong> <%= bus["VEHICLE"] %><br>
    <strong>Next Stop: </strong> <%= bus["TIMEPOINT"] %><br>
  </p>
<% end %>

<% if @buses.empty? %>
  <p>
    No buses nearby...  <%= link_to 'edit your location', edit_location_path(@location) %>.
  </p>
<% end %>


<p>
  <strong>Street address:</strong>
  <%= @location.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>